#!/usr/bin/env bash

# Auto-generated by Bashly v0.9.5
# https://bashly.dannyb.co/
# DO NOT EDIT THIS FILE DIRECTLY. INSTEAD, EDIT THE YAML CONFIGURATION FILE AND REGENERATE.

case_id="${args[caseid]:-$1}"

command_summarize_case() {

  if ! command -v python3 &> /dev/null; then
    echo "Python3 is not installed. Please install it to use this command."
    exit 1
  fi

  python3 $HOME/caseSummaryGenerator.py "$case_id"
}

# Main entry point
command_summarize_case
    